import { Injectable } from '@angular/core';
import { DataManagementService } from './data-management.service';
import { addDoc } from 'firebase/firestore';
import { ContactInterface } from '../interfaces/contact-interface';

@Injectable({
  providedIn: 'root',
})
export class DataBackupService {
  activeTableColumns = [
    {
      index: 0,
      name: 'Contacts',
      type: 'text',
      columnId: '',
      id: '',
      icon: '',
      color: '',
      used: true,
      activeDropdown: {},
      availableDropdowns: [],
    },
    {
      index: 1,
      name: 'Tel.',
      type: 'href',
      columnId: '',
      id: '',
      icon: '',
      color: '',
      used: true,
      activeDropdown: {},
      availableDropdowns: [],
    },
    {
      index: 2,
      name: 'Email',
      type: 'href',
      columnId: '',
      id: '',
      icon: '',
      color: '',
      used: true,
      activeDropdown: {},
      availableDropdowns: [],
    },
    {
      index: 3,
      columnId: '',
      id: '',
      name: 'User Roles',
      type: 'dropdown',
      icon: 'supervised_user_circle',
      color: '#2196f3',
      used: false,
      activeDropdown: { name: '', color: '' },
      availableDropdowns: [
        { name: 'Designer', color: '#d84315' },
        { name: 'Manager', color: '#1976d2' },
        { name: 'Lead', color: '#388e3c' },
        { name: 'Partner', color: '#7b1fa2' },
        { name: 'Developer', color: '#fbc02d' },
      ],
    },
    {
      index: 4,
      columnId: '',
      id: '',
      name: 'Standing',
      type: 'dropdown',
      icon: 'bolt',
      color: '#4caf50',
      used: false,
      activeDropdown: { name: '', color: '' },
      availableDropdowns: [
        { name: 'Active', color: '#4caf50' },
        { name: 'Inactive', color: '#f44336' },
      ],
    },
    {
      index: 5,
      columnId: '',
      id: '',
      name: 'Priority',
      type: 'dropdown',
      icon: 'priority_high',
      color: '#f44336',
      used: false,
      activeDropdown: { name: '', color: '' },
      availableDropdowns: [
        { name: 'high', color: '#f44336' },
        { name: 'medium', color: '#ffc107' },
        { name: 'low', color: '#8bc34a' },
      ],
    },
  ];

  inactiveTableColumns = [
    {
      index: 0,
      name: 'Contacts',
      type: 'text',
      columnId: '',
      id: '',
      icon: '',
      color: '',
      used: true,
      activeDropdown: {},
      availableDropdowns: [{}],
    },
    {
      index: 1,
      name: 'Tel.',
      type: 'href',
      columnId: '',
      id: '',
      icon: '',
      color: '',
      used: true,
      activeDropdown: {},
      availableDropdowns: [{}],
    },
    {
      index: 2,
      name: 'Email',
      type: 'href',
      columnId: '',
      id: '',
      icon: '',
      color: '',
      used: true,
      activeDropdown: {},
      availableDropdowns: [{}],
    },
    {
      index: 3,
      columnId: '',
      id: '',
      name: 'User Roles',
      type: 'dropdown',
      icon: 'supervised_user_circle',
      color: '#2196f3',
      used: false,
      activeDropdown: { name: '', color: '' },
      availableDropdowns: [
        { name: 'Artist', color: '#d84315' },
        { name: 'Manager', color: '#1976d2' },
        { name: 'Lead', color: '#388e3c' },
        { name: 'Partner', color: '#7b1fa2' },
        { name: 'Customer', color: '#fbc02d' },
      ],
    },
    {
      index: 4,
      columnId: '',
      id: '',
      name: 'Standing',
      type: 'dropdown',
      icon: 'bolt',
      color: '#4caf50',
      used: false,
      activeDropdown: { name: '', color: '' },
      availableDropdowns: [
        { name: 'Active', color: '#4caf50' },
        { name: 'Inactive', color: '#f44336' },
      ],
    },
    {
      index: 5,
      columnId: '',
      id: '',
      name: 'Priority',
      type: 'dropdown',
      icon: 'priority_high',
      color: '#f44336',
      used: false,
      activeDropdown: { name: '', color: '' },
      availableDropdowns: [
        { name: 'high', color: '#f44336' },
        { name: 'medium', color: '#ffc107' },
        { name: 'low', color: '#8bc34a' },
      ],
    },
  ];

  activeContacts: ContactInterface[] = [
    {
      id: '1',
      checked: false,
      status: 'active',
      name: 'Max Meier',
      tel: '01514456789',
      email: 'max.meier@gmail.com',
      visibleEmail: 'Max Meier',
      emailEdit: false,
      telEdit: false,
      emailHovered: false,
      telHovered: false,
      timestamp: 3,
      color: '#6A5ACD',
      priorityBadge: {
        name: 'medium',
        color: '#ffc107',
        used: true,
      },
      statusBadge: {
        name: 'Active',
        color: '#4caf50',
        used: true,
      },
      roleBadge: {
        name: 'Manager',
        color: '#1976d2',
        used: true,
      },
    },
    {
      id: '2',
      checked: false,
      status: 'active',
      name: 'Sarah Müller',
      tel: '01513456123',
      email: 'sarah.mueller@web.de',
      visibleEmail: 'Sarah Müller',
      emailEdit: false,
      telEdit: false,
      emailHovered: false,
      telHovered: false,
      timestamp: 4,
      color: '#FF4500',
      priorityBadge: {
        name: 'low',
        color: '#8bc34a',
        used: true,
      },
      statusBadge: {
        name: 'Active',
        color: '#4caf50',
        used: true,
      },
      roleBadge: {
        name: 'Designer',
        color: '#d84315',
        used: true,
      },
    },
    {
      id: '3',
      checked: false,
      status: 'active',
      name: 'Lisa Hoffmann',
      tel: '01511234567',
      email: 'lisa.hoffmann@outlook.com',
      visibleEmail: 'Lisa Hoffmann',
      emailEdit: false,
      telEdit: false,
      emailHovered: false,
      telHovered: false,
      timestamp: 5,
      color: '#CD5C5C',
      priorityBadge: {
        name: 'high',
        color: '#f44336',
        used: true,
      },
      statusBadge: {
        name: 'Active',
        color: '#4caf50',
        used: true,
      },
      roleBadge: {
        name: 'Partner',
        color: '#7b1fa2',
        used: true,
      },
    },
    {
      id: '4',
      checked: false,
      status: 'active',
      name: 'Tom Fischer',
      tel: '01513334455',
      email: 'tom.fischer@yahoo.com',
      visibleEmail: 'Tom Fischer',
      emailEdit: false,
      telEdit: false,
      emailHovered: false,
      telHovered: false,
      timestamp: 6,
      color: '#32CD32',
      priorityBadge: {
        name: 'medium',
        color: '#ffc107',
        used: true,
      },
      statusBadge: {
        name: 'Active',
        color: '#4caf50',
        used: true,
      },
      roleBadge: {
        name: 'Lead',
        color: '#388e3c',
        used: true,
      },
    },
    {
      id: '5',
      checked: false,
      status: 'active',
      name: 'Anna Berger',
      tel: '01516789012',
      email: 'anna.berger@freenet.de',
      visibleEmail: 'Anna Berger',
      emailEdit: false,
      telEdit: false,
      emailHovered: false,
      telHovered: false,
      timestamp: 7,
      color: '#9370DB',
      priorityBadge: {
        name: 'low',
        color: '#8bc34a',
        used: true,
      },
      statusBadge: {
        name: 'Active',
        color: '#4caf50',
        used: true,
      },
      roleBadge: {
        name: 'Developer',
        color: '#fbc02d',
        used: true,
      },
    },
    {
      id: '6',
      checked: false,
      status: 'active',
      name: 'Robert Klein',
      tel: '01519991234',
      email: 'robert.klein@t-online.de',
      visibleEmail: 'Robert Klein',
      emailEdit: false,
      telEdit: false,
      emailHovered: false,
      telHovered: false,
      timestamp: 8,
      color: '#4682B4',
      priorityBadge: {
        name: 'high',
        color: '#f44336',
        used: true,
      },
      statusBadge: {
        name: 'Active',
        color: '#4caf50',
        used: true,
      },
      roleBadge: {
        name: 'Manager',
        color: '#1976d2',
        used: true,
      },
    },
    {
      id: '7',
      checked: false,
      status: 'active',
      name: 'Monika Schulz',
      tel: '01514447890',
      email: 'monika.schulz@gmail.com',
      visibleEmail: 'Monika Schulz',
      emailEdit: false,
      telEdit: false,
      emailHovered: false,
      telHovered: false,
      timestamp: 9,
      color: '#FF6347',
      priorityBadge: {
        name: 'medium',
        color: '#ffc107',
        used: true,
      },
      statusBadge: {
        name: 'Active',
        color: '#4caf50',
        used: true,
      },
      roleBadge: {
        name: 'Designer',
        color: '#d84315',
        used: true,
      },
    },
  ];
  

  inactiveContacts: ContactInterface[] = [
    {
      id: '1',
      checked: false,
      status: 'inactive',
      name: 'Katrin Weber',
      tel: '01515556677',
      email: 'katrin.weber@web.de',
      visibleEmail: 'Katrin Weber',
      emailEdit: false,
      telEdit: false,
      emailHovered: false,
      telHovered: false,
      timestamp: 3,
      color: '#4682B4',
      priorityBadge: {
        name: 'low',
        color: '#8bc34a',
        used: true,
      },
      statusBadge: {
        name: 'Inactive',
        color: '#f44336',
        used: true,
      },
      roleBadge: {
        name: 'Partner',
        color: '#7b1fa2',
        used: true,
      },
    },
    {
      id: '2',
      checked: false,
      status: 'inactive',
      name: 'Frank Neumann',
      tel: '01516667890',
      email: 'frank.neumann@gmail.com',
      visibleEmail: 'Frank Neumann',
      emailEdit: false,
      telEdit: false,
      emailHovered: false,
      telHovered: false,
      timestamp: 4,
      color: '#FF6347',
      priorityBadge: {
        name: 'medium',
        color: '#ffc107',
        used: true,
      },
      statusBadge: {
        name: 'Inactive',
        color: '#f44336',
        used: true,
      },
      roleBadge: {
        name: 'Customer',
        color: '#fbc02d',
        used: true,
      },
    },
    {
      id: '3',
      checked: false,
      status: 'inactive',
      name: 'Uwe Lehmann',
      tel: '01517778899',
      email: 'uwe.lehmann@gmx.de',
      visibleEmail: 'Uwe Lehmann',
      emailEdit: false,
      telEdit: false,
      emailHovered: false,
      telHovered: false,
      timestamp: 5,
      color: '#20B2AA',
      priorityBadge: {
        name: 'low',
        color: '#8bc34a',
        used: true,
      },
      statusBadge: {
        name: 'Inactive',
        color: '#f44336',
        used: true,
      },
      roleBadge: {
        name: 'Artist',
        color: '#d84315',
        used: true,
      },
    },
    {
      id: '4',
      checked: false,
      status: 'inactive',
      name: 'Julia Becker',
      tel: '01518889900',
      email: 'julia.becker@outlook.com',
      visibleEmail: 'Julia Becker',
      emailEdit: false,
      telEdit: false,
      emailHovered: false,
      telHovered: false,
      timestamp: 6,
      color: '#FF4500',
      priorityBadge: {
        name: 'high',
        color: '#f44336',
        used: true,
      },
      statusBadge: {
        name: 'Inactive',
        color: '#f44336',
        used: true,
      },
      roleBadge: {
        name: 'Partner',
        color: '#7b1fa2',
        used: true,
      },
    },
  ];
  

  dealsColumns = [
    {
      index: 0,
      name: 'Deal',
      type: 'text',
      columnId: '',
      id: '',
      icon: '',
      color: '',
      used: true,
      activeDropdown: {},
      availableDropdowns: [],
    },
    {
      index: 1,
      name: 'Value',
      type: 'text',
      columnId: '',
      id: '',
      icon: '',
      color: '',
      used: true,
      activeDropdown: {},
      availableDropdowns: [],
    },
    {
      index: 2,
      name: 'Phase',
      type: 'dropdown',
      columnId: '',
      id: '',
      icon: '',
      color: '',
      used: true,
      activeDropdown: {},
      availableDropdowns: [
        { name: 'Lead', color: '#FFA500', used: false },
        { name: 'Check', color: '#1E90FF', used: false },
        { name: 'Offer', color: '#9370DB', used: false },
        { name: 'Close', color: '#FFD700', used: false },
        { name: 'Won', color: '#32CD32', used: false },
        { name: 'Lost', color: '#FF4500', used: false },
      ],
    },
    {
      index: 3,
      columnId: '',
      id: '',
      name: 'Representative',
      type: 'dropdown',
      icon: '',
      color: '',
      used: true,
      activeDropdown: { name: '', color: '' },
      availableDropdowns: [],
    },
    {
      index: 4,
      columnId: '',
      id: '',
      name: 'Expexted Close Date',
      type: 'date',
      icon: '',
      color: '',
      used: true,
      activeDropdown: {},
      availableDropdowns: [],
    },
  ];

  deals = [
    {
      id: '1',
      checked: false,
      name: 'Deal A',
      phaseBadge: {
        name: 'Lead',
        color: '#FFA500',
        used: true,
      },
      dealValue: 12000,
      responsibleBadge: {
        name: 'John Doe',
        color: '#1E90FF',
        used: true,
      },
      closingDate: '2024-10-31',
      euNormDate: '31.10.2024',
      dateAsTimestamp: 1730332800000,  
      timestamp: 0,
    },
    {
      id: '2',
      checked: false,
      name: 'Deal B',
      phaseBadge: {
        name: 'Check',
        color: '#1E90FF',
        used: true,
      },
      dealValue: 15000,
      responsibleBadge: {
        name: 'Jane Smith',
        color: '#32CD32',
        used: true,
      },
      closingDate: '2024-11-10',
      euNormDate: '10.11.2024',
      dateAsTimestamp: 1731033600000,  
      timestamp: 1,
    },
    {
      id: '3',
      checked: false,
      name: 'Deal C',
      phaseBadge: {
        name: 'Offer',
        color: '#9370DB',
        used: true,
      },
      dealValue: 18000,
      responsibleBadge: {
        name: 'Alice Brown',
        color: '#FFD700',
        used: true,
      },
      closingDate: '2024-12-01',
      euNormDate: '01.12.2024',
      dateAsTimestamp: 1732406400000,  
      timestamp: 2,
    },
    {
      id: '4',
      checked: false,
      name: 'Deal D',
      phaseBadge: {
        name: 'Close',
        color: '#FFD700',
        used: true,
      },
      dealValue: 25000,
      responsibleBadge: {
        name: 'Mike Johnson',
        color: '#4B0082',
        used: true,
      },
      closingDate: '2025-01-15',
      euNormDate: '15.01.2025',
      dateAsTimestamp: 1736947200000,  
      timestamp: 3,
    },
    {
      id: '5',
      checked: false,
      name: 'Deal E',
      phaseBadge: {
        name: 'Won',
        color: '#32CD32',
        used: true,
      },
      dealValue: 50000,
      responsibleBadge: {
        name: 'Sara Connor',
        color: '#FF4500',
        used: true,
      },
      closingDate: '2025-02-28',
      euNormDate: '28.02.2025',
      dateAsTimestamp: 1740748800000,  
      timestamp: 4,
    }
  ];
  

  constructor(private dataManagement: DataManagementService) {
    /* Run this addBackupData() Function in AppComponent.ts to set Backup Data */
  }

  async addBackupData() {
    // for (const contact of this.activeContacts) {
    //   await addDoc(this.dataManagement.getDocRef('activeContacts'), contact);
    // }
    // for (const contact of this.inactiveContacts) {
    //   await addDoc(this.dataManagement.getDocRef('inactiveContacts'), contact);
    // }
    // for (const column of this.activeTableColumns) {
    //   await addDoc(this.dataManagement.getDocRef('activeTableColumns'), column);
    // }
    // for (const column of this.inactiveTableColumns) {
    //   await addDoc(
    //     this.dataManagement.getDocRef('inactiveTableColumns'),
    //     column
    //   );
    // }
    // for (const deal of this.deals) {
    //   await addDoc(this.dataManagement.getDocRef('deals'), deal);
    // }
    // for (const column of this.dealsColumns) {
    //   await addDoc(this.dataManagement.getDocRef('dealsColumns'), column);
    // }
  }
}
